### ISSUE TITLE
Toggled options reset every time I open the game.

### ISSUE THREAD

**Issue by thebigfootsdad** [krafs/Toggles#8]
Every time I load my save, the toggled options I had set return to the default state. I don't know if this is a bug or a feature, but is there any way to keep the things I disabled? 

Thanks 😄

**Comment by krafs** [comment]
I am so sorry for not seeing this until now. My notifications are apparently not working.

I'd been aware of this issue, but hadn't been able to pinpoint the cause until last week. I believe the settings reset when any of the Raid Modes, like Center Drop Pod, were disabled. They weren't saving the right way, and whenever RimWorld finds broken mod settings, it just resets them.
Anyway, I fixed it, and everything should save and reload fine now. Don't hesitate to get back to me if the issue persists.
